### ISSUE TITLE
'lookBackMinutes ' doesn't work

### ISSUE THREAD

**Issue by wisinfun** [thebitguru/alfred-imessage-2fa-copy#1]

**Comment by thebitguru** [comment]
Hello @wisinfun, the [parameter is there](https://github.com/thebitguru/alfred-imessage-2fa-copy/blob/c427bb37bf56245bedc51e4c0cc5e31bbb0e64a1/get_codes.sh#L47) in the query, so I would like to learn more about what you are experiencing. Can you tell me more about how you have it setup? What value are you using?
