### ISSUE TITLE
[BUG / Feature Request] Regex does not match codes containing letters

### ISSUE THREAD

**Issue by hmenzagh** [thebitguru/alfred-imessage-2fa-copy#4]
There is an issue when trying to get back codes that contain letters.
It seems that the regex only accepts digits.
I currently do not have the time to send a PR at the moment, will do if the issue still persists when my schedule frees up a little.

Source of the issue:
https://github.com/thebitguru/alfred-simple-2fa-paste/blob/149ad2e82305a4d0ee1e0e9634b4c116a81202f2/get_codes.sh#L11C1-L11C41

As always, thanks for the great work !

**Comment by thebitguru** [comment]
Thanks for reporting, @hmenzagh. Any chance you can share an example of the code?

**Comment by thebitguru** [comment]
Closing for now since I can't confirm without some example codes. I will reopen if I get examples.
